version: 2.1

orbs:
  cypress: cypress-io/cypress@3.4.3
  mac: circleci/macos@2.5.2
  node: circleci/node@7.1.0
  win: circleci/windows@5.1.0

executors:
  linux:
    docker:
      - image: circleci/buildpack-deps:trusty
        user: root
  macos:
    macos:
      xcode: '16.2.0'
  win: 
    machine:
      image: windows-server-2019-vs2019:current
      resource_class: windows.medium

anchors:
  - &npm_cache_key package-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION }}

  - &os_param
    parameters:
      os:
        type: string

  - &matrix_params
    matrix:
      parameters:
        os: [ 'linux', 'macos', 'win' ]

commands:
  build_install_cli:
    steps:
      - run:
          name: Install CLI dependencies
          command: cd packages/cli && npm install
      - run:
          name: Build CLI
          command: cd packages/cli && npm run build
      - run:
          name: Install CLI
          command: cd packages/cli && npm install -g
      - run:
          name: Quire Version
          command: quire --version

  build_install_cli-linux:
    steps:
      - node/install:
          node-version: "22.14.0"
      - build_install_cli

  build_install_cli-macos:
    steps:
      - node/install:
          node-version: "22.14.0"
      - build_install_cli

  build_install_cli-win:
    steps:
      - build_install_cli

  # install_deps-linux:
  #   steps:
  #     - run:
  #         name: Install External Dependencies
  #         command: |
  #           chmod +x scripts/install-deps-linux.sh
  #           scripts/install-deps-linux.sh

  # install_deps-macos:
  #   steps:
  #     - run:
  #         name: Install External Dependencies
  #         command: |
  #           chmod +x scripts/install-deps-macos.sh
  #           scripts/install-deps-macos.sh

  # install_deps-win:
  #   steps:
  #     - run:
  #         name: Install External Dependencies
  #         shell: powershell.exe
  #         command: .\scripts\install-deps-win.ps1

  run_tests:
    steps:
      # TODO: Create test artifact / result directory
      # - run:
      #     name: Add test report directory
      #     command: mkdir -p test-results
      - run:
          name: Run CLI tests
          command: cd packages/cli && npm run test
      - run:
          name: Run 11ty tests
          command: cd packages/11ty && npm run test
      # TODO: Store test artifacts /results
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results

  test-linux:
    steps:
      # TODO: Don't think we need this anymore? Might be being naive tho
      # - run:
      #     name: Install Cypress Dependencies
      #     command: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run_tests

  test-macos:
    steps:
      - run_tests

  test-win:
    steps:
      - run_tests

jobs:
  build_install_test:
    <<: *os_param
    executor: << parameters.os >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - *npm_cache_key
      - build_install_cli-<< parameters.os >>
      - install_deps-<< parameters.os >>
      - test-<< parameters.os >>
      - save_cache:
          key: *npm_cache_key
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache

workflows:
  build_install_test:
    # TODO: Update this with tests against branch (eg, don't run for docs/, etc)
    when: true
    jobs:
      - build_install_test:
          <<: *matrix_params
          name: build_install_test-<< matrix.os >>
