baseURL: ''
disableKinds:
  - home
  - section
  - taxonomy
  - term
footnoteReturnLinkContents: "↩"
GoogleAnalytics: ''
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true # allows HTML tags within Markdown file
metaDataFormat: yaml
pluralizeListTitles: true
publishDir: site
theme: default
title: Quire Starter
params:
  biblioHeading: Bibliography
  citationPageLocationDivider: ", "
  citationPopupStyle: text # text | icon
  contributorByline: name-title # name | name-title | false
  displayBiblioShort: true
  entryPageObjectLinkText: View in Collection
  entryPageSideBySideLayout: false
  figureLabelLocation: on-top # below | on-top
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  imageDir: img
  licenseIcons: true
  menuType: full
  nextPageButtonText: Next
  pageLabelDivider: ". "
  prevPageButtonText: Back
  searchEnabled: true
  tocType: full
